sudo: required
language: ruby
rvm:
  - 2.3.2
services:
  - docker
before_install:
  - docker-compose up -d
script:
  - bundle exec rubocop --rails
  - bundle exec rake db:test:prepare
  - bundle exec rails spec
