version: '2'
services:
  app:
    build: .
    command: bin/rails server -b '0.0.0.0'
    volumes:
      - .:/kitahub
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://db
  db:
    image: postgres:9.5.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kitahub
