version: '2'
services:
  postgres:
    image: postgres:9.5.4
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=kitahub

  redis:
    image: redis:3.2.3
    ports:
      - "6379:6379"
